language: php
os: linux
dist: bionic

addons:
  apt:
    packages:
      - mysql-server-5.7
      - mysql-client-core-5.7
      - mysql-client-5.7
    
php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

env:
# Here we list the profiles that we want to test, each one will be tested, per version of PHP, in parallel
#- PROFILE=default

before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
  # Remove xdebug to increase speed
  - phpenv config-rm xdebug.ini
  # Set up database
  - tests/database_setup.sh

install:
  # Create setup.php
  - export PROFILE=${PROFILE:-testing}
  - ln -s .travis.setup.php setup.php
  - composer self-update
  - composer update
  # Install the testing profile
  - tests/profile_setup.sh "$PROFILE"

before_script:
# execute all of the commands which need to be executed
# before running actual tests

script:
  # execute all of the commands which
  # should make the build pass or fail
  # Go into the tests directory to run the tests
  - cd tests/
  - ../vendor/phpunit/phpunit/phpunit

branches:
  only:
    - develop
    - master
    - master-fix
